version: '3'

services:

  nginx:
    container_name: nginx
    build:
        context: ./nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./frontend/build:/var/www/html
    networks:
      - mynetwork

  backend: 
    container_name: backend
    build:
      context: ./backend
    restart: always
    depends_on:
      - database
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - 'frontend_modules:/app/node_modules'
    networks:
      - mynetwork


  database:
    image: mariadb
    restart: always
    env_file: 
      - ./backend/.env
    volumes:
      - db_data:/var/lib/mysql
      - ./backend:/app
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    depends_on:
      - database
    env_file: 
      - ./backend/.env
    networks:
      - mynetwork

volumes:
  db_data:
  frontend:
  frontend_modules:

networks:
  mynetwork: {}